#+LATEX_CLASS: revtex4-1
#+LATEX_CLASS_OPTIONS: [aps,prl,preprint,citeautoscript,showkeys,floatfix]
#+OPTIONS: toc:nil author:nil ^:{}
#+EXPORT_EXCLUDE_TAGS: noexport

#+BIND: org-latex-title-command nil

\title{NRQCD Quarkonia Production in Sherpa}
\author{David Bjergaard}
\author{Frank Krauss}
\date{\today}

#+BEGIN_abstract
We describe the implementation and validation of quarkonia production
using non-relativistic QCD matrix elements in Sherpa.  We validate the
implementation using properties of the matrix element as well as
comparing to the cross section measured by ATLAS at 7 TeV.  We present
a comparison to Pythia and discuss differences in the modeling
assumptions used.  Finally we present a novel method of extracting the
long distance matrix elements needed for experimental comparison to
data. 
#+END_abstract

\maketitle

* Introduction
:PROPERTIES:
:CUSTOM_ID: sec:intro
:END:
The production and dynamics of heavy quark bound states (quarkonia)
simultaneously probe perturbative and non-perturbative aspects of
quantum chromodynamics (QCD).  The charmonium system has yielded many
surprises since its discovery in 1974 \cite{PhysRevLett.33.1404}
\cite{PhysRevLett.33.1406}. In particular, the cross section measured
at the Tevatron was found to be significantly higher than the leading
order calculation assuming color singlet production
\cite{PhysRevlett.79.572}. This lead to the introduction of terms
arising from the non-relativistic expansion of the QCD lagrangian
(NRQCD).  

The production and propagation of a bound quark system can be split
into two scales: the hard process scale, and the relative motion of
the quarks.  The relative velocity of the quarks ($v$) is assumed to
be small enough that a hierarchy is formed between the hard scale (the
quarkonia mass $m$), the momentum, and the kinetic energy
\cite{Pineda:2011dg}:
#+BEGIN_LaTeX
\begin{equation}
m \gg mv \gg mv^2
\end{equation}
#+END_LaTeX

This separation of scales allows a double expansion in the relative
motion of the quarks (in powers of $v$) and a traditional expansion in
$\alpha_S$ the strong coupling constant.  This framework provides
strong predictions about the kinematic dependence of the matrix
elements in quarkonia production.  The partonic cross section can be
expressed as:
#+BEGIN_LaTeX
  \begin{equation}
  \label{eq:xs_total}
  \frac{d\sigma}{d\hat{t}}(ab \rightarrow Q\overline{Q}[n] c \rightarrow
  \psi_Q) = \frac{1}{16 \pi \hat{s}^2}
  \overline{\sum}\left|\mathcal{A}(ab \rightarrow Q\overline{Q}[n] c)_{\text{short}}\right|^2\langle 0 | O^{\psi_Q}_{8,1}(n) |0 \rangle
  \end{equation}
#+END_LaTeX
Here, $a,b$ and $c$ represent initial and final state partons, $n$
represents the quantum numbers required to specify the state, and
$\psi_{Q}$ is the final state hadron.  The sum is understood to be the
average over initial spin and color states of the scattering
amplitudes and the $\langle 0 | O^{\psi_Q}_{8,1}(n) |0 \rangle$ term
(abbreviated as $\mathcal{O}^H_{8,1}(n)$) is the long distance matrix
element (LDME). The quantum numbers $n$ are typically given in
spectroscopic notation as $^{2S+1}L_{J}^{(8,1)}$ where the additional
index indicates singlet (1) or octet (8).

Unfortunately this factorization leaves a number of parameters
undetermined which must be measured by experiment (the LDMEs).  These
parameters represent the non-perturbative aspects of the production,
allowing the perturbative parts (including kinematic dependence) to be
factored out and calculated using perturbation theory.

NRQCD does not provide a prescription for how to extract the LDMEs
from data.  This is further complicated by the spectrum of the
charmonium system since higher excited singlet states "feed down" to
the lowest J/\psi state.  Furthermore, there is no consensus on which
data should be included in the fits CITEME, or which LDMEs are
appropriate given a kinematic regime probed by an experiment CITEME.

The rest of the paper is organized as follows: in section
[[Methods]] the implementation of the matrix elements is
discussed, including assumptions and organizations which impact the
user.  In [[Results]] the results of the implementation are
compared to ATLAS 2011 data at 7 TeV and are compared to Pythia's
prediction. Additionally, the results of extracting LDMEs from Sherpa
directly are presented. Finally we conclude in [[Conclusion]]
with remarks on the state of the art as well as future directions for
modeling and experiment.  In the appendix ([[Appendix]]) the
functional form of the matrix elements is collected for each of the
quarkonia states. 

* Methods
:PROPERTIES:
:CUSTOM_ID: sec:methods
:END: 
** Singlet
The matrix elements which arise from color singlet states have been
available in the literature for quite some time \cite{Gastmans:1986qv}
\cite{Humpert:1986cy} \cite{Quigg:1979vr} and more recently
\cite{Eichten:1995ch}. Typically the scale of the matrix element is
related to to the wave function (or its derivatives) at the origin.
The kinematic dependence is determined by evaluating the Feynman
diagrams contributing to a process. In order to keep the treatment of
the matrix elements agnostic of singlet or octet initiated states,
our implementation  only considers LDMEs. The relation is \cite{Bodwin:1994jh}:
#+BEGIN_LaTeX
\begin{equation}
\mathcal{O}^{H}_1(^{2S+1}L_{J}) = \frac{(2L+1)N_{c}}{2\pi}|\overline{R_{H}}|^2
\end{equation}
#+END_LaTeX

** Octet
The non-relativistic expansion of the QCD lagrangian gives rise to
Feynman rules which produce pairs of heavy quarks in a color octet
state.  These states must then radiate at least one gluon in order to
transition to a color singlet hadron.  The color octet LDMEs are
extracted by fitting the functional forms of the kinematic cross
sections to the data.  Fits may select different regions of phase
space \cite{Gong:2012ug}, include or exclude feed-down effects
\cite{Butenschoen:2012qr} or exclude production mechanisms
\cite{Faccioli:2014cqa}. It is important that the experimental
practitioner know what goes into a set of matrix elements before
comparing them to new experimental data.

** Shedding color charge
While NRQCD provides a mechanism for factorizing non-perturbative
effects from those that can be calculated perturbatively it does not
provide a prescription for how to handle the color charge of the octet
state as propagates through space. Here we follow the same approach as
Pythia and allow the octet state to radiate as a heavy gluon
\cite{Sjostrand:2007gs}.  The last emission of the quarkonia is a soft
gluon which allows the quarkonia to transition to a color singlet.
The merits of this approximation are discussed in the Pythia manual
under "Timelike Showers". 

** Gluon initiated states
Processes which have two gluons in the initial state, must have at
least one gluon in the final state.  This produces a high degree of
symmetry in the expressions for the matrix elements when expressed in
terms of the partonic Mandelstam variables. It is possible to recast
the mandelstam variables to make this symmetry manifest \cite{Ma:2012ex}:
#+BEGIN_LaTeX
\begin{align}
 S_1& = s + t + u \\
 S_2& = st + tu + us \\
 S_3& = stu
\end{align}
#+END_LaTeX
It is clear from inspection that these variables are symmetric under
exchanges $s\leftrightarrow t$, $u\leftrightarrow s$ and $t
\leftrightarrow u$. By following the prescription for simplifying
expressions of $s,t$ and $u$ in terms of $S_1,S_2$ and $S_3$, the
expressions are shortened on average by a factor of 5-6.  This not
only makes it easier to verify the correctness of the implemented
formula, it provides a similar performance increase in the time it
takes to run the simulation.  

** Extracting LDMEs
* Results
:PROPERTIES:
:CUSTOM_ID: sec:results
:END: 
** Comparison to Pythia 8
** Comparison to ATLAS
** Extracted LDMEs
* Conclusion
:PROPERTIES:
:CUSTOM_ID: sec:conclusion
:END: 
\bibliography{sherpa-octet-paper}
* Appendix
:PROPERTIES:
:CUSTOM_ID: sec:appendix
:END: 
Here we collect the short distance matrix elements as implemented in
Sherpa.  Where appropriate, the gluon initiated processes have been
simplified using new variables $S_1,S_2$ and $S_3$. See the body of
the main text for a definition and discussion of these variables.

** Singlet $^1S_0^{(1)}$ 
#+BEGIN_LaTeX
\begin{align}
\overline{\sum}\left|\mathcal{A}(q\bar{q} \rightarrow Q\overline{Q}[^1S_0^{(1)}] g)\right|^2 &= \frac{(4\pi\alpha_s)^3}{27 M} \left(\frac{t}{s}\right)^2\frac{(s-M^2)^2-2 t u}{s (s-M^2)^2}\\
\overline{\sum}\left|\mathcal{A}(gq \rightarrow Q\overline{Q}[^1S_0^{(1)}] q)\right|^2 &= -\frac{8}{3}\frac{(4\pi\alpha_s)^3}{27 M}\frac{(t-M^2)^2-2 s u}{t(t-M^2)^2}\\
\overline{\sum}\left|\mathcal{A}(gg \rightarrow Q\overline{Q}[^1S_0^{(1)}] g)\right|^2 &= \frac{(4\pi\alpha_s)^3}{48 M} \left( \frac{M^4-(s^2+t^2+u^2)}{(s-M^2)(t-M^2)(u-M^2)} \right)^2\frac{M^8+s^4+t^4+u^4}{s t u}
\end{align}
#+END_LaTeX
** Octet $^1S_0^{(8)}$ 
#+BEGIN_LaTeX
\begin{align}
\overline{\sum}\left|\mathcal{A}(q\bar{q} \rightarrow Q\overline{Q}[^1S_0^{(8)}] g)\right|^2 &= \frac{5(4\pi \alpha_s)^3}{27 M}\frac{t^2 + u^2}{s(s-M^2)^2} \\
\overline{\sum}\left|\mathcal{A}(gq \rightarrow Q\overline{Q}[^1S_0^{(8)}] q)\right|^2 &= -\frac{5(4\pi \alpha_s)^3}{72 M}\frac{s^2 + u^2}{t(t-M^2)^2} \\
\overline{\sum}\left|\mathcal{A}(gg \rightarrow Q\overline{Q}[^1S_0^{(8)}] g)\right|^2 &= \frac{5(4\pi \alpha_s)^3}{16 M} \frac{(S_2^2 - S_1 S_3)(S_1^4+2 S_1^2 S_2 + S_2^2 + 2 S_1 S_3)}{(S_3(S_1 S_2 + S_3))^2} 
\end{align}
#+END_LaTeX
** Singlet $^3S_1^{(1)}$ 
#+BEGIN_LaTeX
\begin{multline}
\overline{\sum}\left|\mathcal{A}(gg \rightarrow Q\overline{Q}[^3S_1^{(1)}] g)\right|^2 = \frac{5 (4\pi\alpha_s)^3 M}{54} \\ 
\left(\frac{s^2}{(t-M^2)^2(u-M^2)^2} + \frac{t^2}{(u-M^2)^2(s-M^2)^2} + \frac{u^2}{(s-M^2)^2(t-M^2)^2} \right) \\
\end{multline}
#+END_LaTeX
** Octet $^3S_1^{(8)}$ 
#+BEGIN_LaTeX
\begin{align}
\overline{\sum}\left|\mathcal{A}(q\bar{q} \rightarrow Q\overline{Q}[^3S_1^{(8)}] g)\right|^2 &= \frac{2(4\pi \alpha_s)^3}{81 M^3}\frac{4(t^2+u^2)-t u}{(s-M^2)^4}\left(4M^2 s + \frac{(s^2+M^4)(t^2+u^2)}{t u}\right)\\
\overline{\sum}\left|\mathcal{A}(gq \rightarrow Q\overline{Q}[^3S_1^{(8)}] q)\right|^2 &= \frac{(4\pi\alpha_s)^3}{108 M^3}\frac{4(s^2+u^2)-s u}{((s-M^2)(t-M^2))^2}\left(2M^2 t + \frac{(s-M^2)^2-2M^2 s t u}{s u}\right)\\
\overline{\sum}\left|\mathcal{A}(gg \rightarrow Q\overline{Q}[^3S_1^{(8)}] g)\right|^2 &= \begin{aligned}[t] -\frac{(4\pi\alpha_s)^3}{144 M^3} & s^2 ((s-M^2)^4 + t^4 + 2 M^4 (t u / s)^2 + u^4) \\
&\times \frac{ (27 (s t + t u + u s)-19 M^4 )}{((s-M^2)^4 (t-M^2)^2 (u-M^2)^2)} \end{aligned}
\end{align}
#+END_LaTeX
** Singlet $^3P_0^{(1)}$ 
#+BEGIN_LaTeX
\begin{align}
\overline{\sum}\left|\mathcal{A}(q\bar{q} \rightarrow Q\overline{Q}[^3P_0^{(1)}] g)\right|^2 &= \frac{4 (4\pi\alpha_s)^3}{9 M^3} \frac{8 t^2}{3 s^2}\frac{(s-3M^2)^2(t^2+u^2)}{s(s-M^2)^4}\\
\overline{\sum}\left|\mathcal{A}(gq \rightarrow Q\overline{Q}[^3P_0^{(1)}] q)\right|^2 &= -\frac{4 (4\pi\alpha_s)^3}{9 M^3} \frac{(t-3M^2)^2(s^2+u^2)}{t(t-M^2)^4}\\
\overline{\sum}\left|\mathcal{A}(gg \rightarrow Q\overline{Q}[^3P_0^{(1)}] g)\right|^2 &= \begin{aligned}[t]\frac{(4\pi\alpha_s)^3}{9M^3(S_3 (S_1 S_2 + S_3)^4)}&(2 (9 S_1^6 S_2^4 + 18 S_1^4 S_2^5 + 9 S_1^2 S_2^6 + 12 S_1^5 S_2^3 S_3 \\
&+ 30 S_1^3 S_2^4 S_3 + 6 S_1 S_2^5 S_3 - S_1^4 S_2^2 S_3^2 + 2 S_1^2 S_2^3 S_3^2 \\
&+ S_2^4 S_3^2 - 2 S_1^3 S_2 S_3^3 - 2 S_1 S_2^2 S_3^3 + 6 S_1^2 S_3^4)) \end{aligned}
\end{align}
#+END_LaTeX
** Octet $^3P_0^{(8)}$ 
#+BEGIN_LaTeX
\begin{align}
\overline{\sum}\left|\mathcal{A}(q\bar{q} \rightarrow Q\overline{Q}[^3P_0^{(8)}] g)\right|^2 &= \frac{20(4\pi\alpha_s)^3}{81M^3}\frac{(s-3M^2)^2(t^2+u^2)}{s(s-M^2)^4}\\
\overline{\sum}\left|\mathcal{A}(gq \rightarrow Q\overline{Q}[^3P_0^{(8)}] q)\right|^2 &= -\frac{5(4\pi\alpha_s)^3}{54M^3} \frac{t[s^2(s-M^2)^2+u^2(s+M^2)^2]}{(t-M^2)^4(s-M^2)^2}\\
\overline{\sum}\left|\mathcal{A}(gg \rightarrow Q\overline{Q}[^3P_0^{(8)}] g)\right|^2 &= \begin{aligned}[t] \frac{5(4\pi\alpha_s)^3}{ 12 M^3 S_3 (S_1 S_2 + S_3)^4}(&9 S_1^6 S_2^4 + 18 S_1^4 S_2^5 + 9 S_1^2 S_2^6 \\
&- 9 S_1^7 S_2^2 S_3 - 3 S_1^5 S_2^3 S_3 + 27 S_1^3 S_2^4 S_3 + 6 S_1 S_2^5 S_3 \\
&- 18 S_1^6 S_2 S_3^2 - 32 S_1^4 S_2^2 S_3^2 + 4 S_1^2 S_2^3 S_3^2 \\
&+ S_2^4 S_3^2 - 13 S_1^5 S_3^3 - 11 S_1^3 S_2 S_3^3 - S_1 S_2^2 S_3^3 \\ 
&+ 5 S_1^2 S_3^4) \end{aligned}
\end{align}
#+END_LaTeX
** Singlet $^3P_1^{(1)}$ 
#+BEGIN_LaTeX
\begin{align}
\overline{\sum}\left|\mathcal{A}(q\bar{q} \rightarrow Q\overline{Q}[^3P_1^{(1)}] g)\right|^2 &= \\
\overline{\sum}\left|\mathcal{A}(gq \rightarrow Q\overline{Q}[^3P_1^{(1)}] q)\right|^2 &= \\
\overline{\sum}\left|\mathcal{A}(gg \rightarrow Q\overline{Q}[^3P_1^{(1)}] g)\right|^2 &= 
\end{align}
#+END_LaTeX
** Octet $^3P_1^{(8)}$ 
#+BEGIN_LaTeX
\begin{align}
\overline{\sum}\left|\mathcal{A}(q\bar{q} \rightarrow Q\overline{Q}[^3P_1^{(8)}] g)\right|^2 &= \\
\overline{\sum}\left|\mathcal{A}(gq \rightarrow Q\overline{Q}[^3P_1^{(8)}] q)\right|^2 &= \\
\overline{\sum}\left|\mathcal{A}(gg \rightarrow Q\overline{Q}[^3P_1^{(8)}] g)\right|^2 &= \\
\end{align}
#+END_LaTeX

** Singlet $^3P_2^{(1)}$ 
#+BEGIN_LaTeX
\begin{align}
\overline{\sum}\left|\mathcal{A}(q\bar{q} \rightarrow Q\overline{Q}[^3P_2^{(1)}] g)\right|^2 &= \\
\overline{\sum}\left|\mathcal{A}(gq \rightarrow Q\overline{Q}[^3P_2^{(1)}] q)\right|^2 &= \\
\overline{\sum}\left|\mathcal{A}(gg \rightarrow Q\overline{Q}[^3P_2^{(1)}] g)\right|^2 &= 
\end{align}
#+END_LaTeX
** Octet $^3P_1^{(8)}$ 
#+BEGIN_LaTeX
\begin{align}
\overline{\sum}\left|\mathcal{A}(q\bar{q} \rightarrow Q\overline{Q}[^3P_2^{(8)}] g)\right|^2 &= \\
\overline{\sum}\left|\mathcal{A}(gq \rightarrow Q\overline{Q}[^3P_2^{(8)}] q)\right|^2 &= \\
\overline{\sum}\left|\mathcal{A}(gg \rightarrow Q\overline{Q}[^3P_2^{(8)}] g)\right|^2 &= \\
\end{align}
#+END_LaTeX

* Quickstart Manual
